/*
 * Copyright (C) 2026 Zhou Qiankang <wszqkzqk@qq.com>
 *
 * SPDX-License-Identifier: LGPL-3.0-or-later
 *
 * This file is part of PvZ-Portable.
 *
 * PvZ-Portable is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * PvZ-Portable is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with PvZ-Portable. If not, see <https://www.gnu.org/licenses/>.
 */

// This file is included by EffectSystem.cpp and should not be built directly by the project.

#define TRI0 0
#define TRI2 0
#define TRI3 0
#define TRI4 0
#define TRI5 0
#include "PvzpDrawTriangle.inc"

#undef TRI5
#define TRI5 1
#include "PvzpDrawTriangle.inc"

#undef TRI5
#undef TRI4
#define TRI4 1
#define TRI5 0
#include "PvzpDrawTriangle.inc"

#undef TRI5
#define TRI5 1
#include "PvzpDrawTriangle.inc"

#undef TRI5
#undef TRI4
#undef TRI3
#define TRI3 1
#define TRI4 0
#define TRI5 0
#include "PvzpDrawTriangle.inc"

#undef TRI5
#define TRI5 1
#include "PvzpDrawTriangle.inc"

#undef TRI5
#undef TRI4
#define TRI4 1
#define TRI5 0
#include "PvzpDrawTriangle.inc"

#undef TRI5
#define TRI5 1
#include "PvzpDrawTriangle.inc"

#undef TRI5
#undef TRI4
#undef TRI3
#undef TRI2
#define TRI2 1
#define TRI3 0
#define TRI4 0
#define TRI5 0
#include "PvzpDrawTriangle.inc"

#undef TRI5
#define TRI5 1
#include "PvzpDrawTriangle.inc"

#undef TRI5
#undef TRI4
#define TRI4 1
#define TRI5 0
#include "PvzpDrawTriangle.inc"

#undef TRI5
#define TRI5 1
#include "PvzpDrawTriangle.inc"

#undef TRI5
#undef TRI4
#undef TRI3
#define TRI3 1
#define TRI4 0
#define TRI5 0
#include "PvzpDrawTriangle.inc"

#undef TRI5
#define TRI5 1
#include "PvzpDrawTriangle.inc"

#undef TRI5
#undef TRI4
#define TRI4 1
#define TRI5 0
#include "PvzpDrawTriangle.inc"

#undef TRI5
#define TRI5 1
#include "PvzpDrawTriangle.inc"

#undef TRI5
#undef TRI4
#undef TRI3
#undef TRI2
#undef TRI0
#define TRI0 1
#define TRI2 0
#define TRI3 0
#define TRI4 0
#define TRI5 0
#include "PvzpDrawTriangle.inc"

#undef TRI5
#define TRI5 1
#include "PvzpDrawTriangle.inc"

#undef TRI5
#undef TRI4
#define TRI4 1
#define TRI5 0
#include "PvzpDrawTriangle.inc"

#define NAME_ADDITIVE
#include "PvzpDrawTriangle.inc"
#undef NAME_ADDITIVE

#undef TRI5
#define TRI5 1
#include "PvzpDrawTriangle.inc"

#define NAME_ADDITIVE
#include "PvzpDrawTriangle.inc"
#undef NAME_ADDITIVE

#undef TRI5
#undef TRI4
#undef TRI3
#define TRI3 1
#define TRI4 0
#define TRI5 0
#include "PvzpDrawTriangle.inc"

#define NAME_ADDITIVE
#include "PvzpDrawTriangle.inc"
#undef NAME_ADDITIVE

#undef TRI5
#define TRI5 1
#include "PvzpDrawTriangle.inc"

#define NAME_ADDITIVE
#include "PvzpDrawTriangle.inc"
#undef NAME_ADDITIVE

#undef TRI5
#undef TRI4
#define TRI4 1
#define TRI5 0
#include "PvzpDrawTriangle.inc"

#define NAME_ADDITIVE
#include "PvzpDrawTriangle.inc"
#undef NAME_ADDITIVE

#undef TRI5
#define TRI5 1
#include "PvzpDrawTriangle.inc"

#define NAME_ADDITIVE
#include "PvzpDrawTriangle.inc"
#undef NAME_ADDITIVE

#undef TRI5
#undef TRI4
#undef TRI3
#undef TRI2
#define TRI2 1
#define TRI3 0
#define TRI4 0
#define TRI5 0
#include "PvzpDrawTriangle.inc"

#define NAME_ADDITIVE
#include "PvzpDrawTriangle.inc"
#undef NAME_ADDITIVE

#undef TRI5
#define TRI5 1
#include "PvzpDrawTriangle.inc"

#define NAME_ADDITIVE
#include "PvzpDrawTriangle.inc"
#undef NAME_ADDITIVE

#undef TRI5
#undef TRI4
#define TRI4 1
#define TRI5 0
#include "PvzpDrawTriangle.inc"

#define NAME_ADDITIVE
#include "PvzpDrawTriangle.inc"
#undef NAME_ADDITIVE

#undef TRI5
#define TRI5 1
#include "PvzpDrawTriangle.inc"

#define NAME_ADDITIVE
#include "PvzpDrawTriangle.inc"
#undef NAME_ADDITIVE

#undef TRI5
#undef TRI4
#undef TRI3
#define TRI3 1
#define TRI4 0
#define TRI5 0
#include "PvzpDrawTriangle.inc"

#define NAME_ADDITIVE
#include "PvzpDrawTriangle.inc"
#undef NAME_ADDITIVE

#undef TRI5
#define TRI5 1
#include "PvzpDrawTriangle.inc"

#define NAME_ADDITIVE
#include "PvzpDrawTriangle.inc"
#undef NAME_ADDITIVE

#undef TRI5
#undef TRI4
#define TRI4 1
#define TRI5 0
#include "PvzpDrawTriangle.inc"

#define NAME_ADDITIVE
#include "PvzpDrawTriangle.inc"
#undef NAME_ADDITIVE

#undef TRI5
#define TRI5 1
#include "PvzpDrawTriangle.inc"

#define NAME_ADDITIVE
#include "PvzpDrawTriangle.inc"
#undef NAME_ADDITIVE

#undef TRI5
#undef TRI4
#undef TRI3
#undef TRI2
#undef TRI0
#define TRI0 2
#define TRI2 0
#define TRI3 0
#define TRI4 0
#define TRI5 0
#include "PvzpDrawTriangle.inc"

#undef TRI5
#define TRI5 1
#include "PvzpDrawTriangle.inc"

#undef TRI5
#undef TRI4
#define TRI4 1
#define TRI5 0
#include "PvzpDrawTriangle.inc"

#define NAME_ADDITIVE
#include "PvzpDrawTriangle.inc"
#undef NAME_ADDITIVE

#undef TRI5
#define TRI5 1
#include "PvzpDrawTriangle.inc"

#define NAME_ADDITIVE
#include "PvzpDrawTriangle.inc"
#undef NAME_ADDITIVE

#undef TRI5
#undef TRI4
#undef TRI3
#define TRI3 1
#define TRI4 0
#define TRI5 0
#include "PvzpDrawTriangle.inc"

#define NAME_ADDITIVE
#include "PvzpDrawTriangle.inc"
#undef NAME_ADDITIVE

#undef TRI5
#define TRI5 1
#include "PvzpDrawTriangle.inc"

#define NAME_ADDITIVE
#include "PvzpDrawTriangle.inc"
#undef NAME_ADDITIVE

#undef TRI5
#undef TRI4
#define TRI4 1
#define TRI5 0
#include "PvzpDrawTriangle.inc"

#define NAME_ADDITIVE
#include "PvzpDrawTriangle.inc"
#undef NAME_ADDITIVE

#undef TRI5
#define TRI5 1
#include "PvzpDrawTriangle.inc"

#define NAME_ADDITIVE
#include "PvzpDrawTriangle.inc"
#undef NAME_ADDITIVE

#undef TRI5
#undef TRI4
#undef TRI3
#undef TRI2
#define TRI2 1
#define TRI3 0
#define TRI4 0
#define TRI5 0
#include "PvzpDrawTriangle.inc"

#define NAME_ADDITIVE
#include "PvzpDrawTriangle.inc"
#undef NAME_ADDITIVE

#undef TRI5
#define TRI5 1
#include "PvzpDrawTriangle.inc"

#define NAME_ADDITIVE
#include "PvzpDrawTriangle.inc"
#undef NAME_ADDITIVE

#undef TRI5
#undef TRI4
#define TRI4 1
#define TRI5 0
#include "PvzpDrawTriangle.inc"

#define NAME_ADDITIVE
#include "PvzpDrawTriangle.inc"
#undef NAME_ADDITIVE

#undef TRI5
#define TRI5 1
#include "PvzpDrawTriangle.inc"

#define NAME_ADDITIVE
#include "PvzpDrawTriangle.inc"
#undef NAME_ADDITIVE

#undef TRI5
#undef TRI4
#undef TRI3
#define TRI3 1
#define TRI4 0
#define TRI5 0
#include "PvzpDrawTriangle.inc"

#define NAME_ADDITIVE
#include "PvzpDrawTriangle.inc"
#undef NAME_ADDITIVE

#undef TRI5
#define TRI5 1
#include "PvzpDrawTriangle.inc"

#define NAME_ADDITIVE
#include "PvzpDrawTriangle.inc"
#undef NAME_ADDITIVE

#undef TRI5
#undef TRI4
#define TRI4 1
#define TRI5 0
#include "PvzpDrawTriangle.inc"

#define NAME_ADDITIVE
#include "PvzpDrawTriangle.inc"
#undef NAME_ADDITIVE

#undef TRI5
#define TRI5 1
#include "PvzpDrawTriangle.inc"

#define NAME_ADDITIVE
#include "PvzpDrawTriangle.inc"
#undef NAME_ADDITIVE

#undef TRI5
#undef TRI4
#undef TRI3
#undef TRI2
#undef TRI0
#define TRI0 3
#define TRI2 0
#define TRI3 0
#define TRI4 0
#define TRI5 0
#include "PvzpDrawTriangle.inc"

#undef TRI5
#define TRI5 1
#include "PvzpDrawTriangle.inc"

#undef TRI5
#undef TRI4
#define TRI4 1
#define TRI5 0
#include "PvzpDrawTriangle.inc"

#undef TRI5
#define TRI5 1
#include "PvzpDrawTriangle.inc"

#undef TRI5
#undef TRI4
#undef TRI3
#define TRI3 1
#define TRI4 0
#define TRI5 0
#include "PvzpDrawTriangle.inc"

#undef TRI5
#define TRI5 1
#include "PvzpDrawTriangle.inc"

#undef TRI5
#undef TRI4
#define TRI4 1
#define TRI5 0
#include "PvzpDrawTriangle.inc"

#undef TRI5
#define TRI5 1
#include "PvzpDrawTriangle.inc"

#undef TRI5
#undef TRI4
#undef TRI3
#undef TRI2
#define TRI2 1
#define TRI3 0
#define TRI4 0
#define TRI5 0
#include "PvzpDrawTriangle.inc"

#undef TRI5
#define TRI5 1
#include "PvzpDrawTriangle.inc"

#undef TRI5
#undef TRI4
#define TRI4 1
#define TRI5 0
#include "PvzpDrawTriangle.inc"

#undef TRI5
#define TRI5 1
#include "PvzpDrawTriangle.inc"

#undef TRI5
#undef TRI4
#undef TRI3
#define TRI3 1
#define TRI4 0
#define TRI5 0
#include "PvzpDrawTriangle.inc"

#undef TRI5
#define TRI5 1
#include "PvzpDrawTriangle.inc"

#undef TRI5
#undef TRI4
#define TRI4 1
#define TRI5 0
#include "PvzpDrawTriangle.inc"

#undef TRI5
#define TRI5 1
#include "PvzpDrawTriangle.inc"

#undef TRI5
#undef TRI4
#undef TRI3
#undef TRI2
#undef TRI0
